name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@main

    - name: Install dependencies
      run: make
      
    - name: Run Lembrete
      run: make lembrete
      
    - name: Run Tests
      run: make test
